version: '3'

services:
  parquimetrodb:
    image: mongo:latest
    container_name: parquimetrodb
    ports:
      - 27017:27017
  app:
    depends_on:
      - parquimetrodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST: localhost
      JWT_SECRET: test-jwt-secret
      JWT_ISSUER: test-jwt-issuer
