version: '3'

services:
  parquimetrodb:
    image: mongo:latest
    container_name: "parquimetrodb"
    ports:
      - 27015:27017
  app:
    depends_on:
      - parquimetrodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST: mongodb
      PORT: parquimetrodb
      DATABASE: parquimetro
      JWT_SECRET: test-jwt-secret
      JWT_ISSUER: test-jwt-issuer
    links:
      - parquimetrodb
